flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:ekmett/quine.git
    commit: da2e3a4531bed0fe39a680b123c460dad0750da2
extra-deps:
- gloss-1.10.2.3
- gloss-raster-1.10.2.3
- gloss-rendering-1.10.3.3
resolver: lts-6.17
