flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- gloss-1.10.2.3
- gloss-algorithms-1.10.2.3
- gloss-raster-1.10.2.3
- gloss-rendering-1.10.3.3
- repa-3.4.0.1
- repa-algorithms-3.4.0.1
- repa-io-3.4.0.1
- vector-0.10.12.3
resolver: lts-6.16
